### ISSUE TITLE
Opening an empty link for me

### ISSUE THREAD

**Issue by Archie-2021** [yekingyan/obsidian-open-in-other-editor#1]
For VSCode it works fine but for gVim it ommits my Vault name in the path, so opening an empty (new note). Very starnge.

Thank you , I looking for such an plugin for a while.

**Comment by yekingyan** [comment]
Hi, what is the platform you are using? I use the Windows platform and use gVim more frequently.
It's strange because they have the same call logic.
I'd like to see the file path when you get an error.
(If the file name is split by spaces, it will have problems. I have fixed this problem in version 0.0.4)

**Comment by Archie-2021** [comment]
> Hi, what is the platform you are using? I use the Windows platform and use gVim more frequently.
> It's strange because they have the same call logic.
> I'd like to see the file path when you get an error.
> (If the file name is split by spaces, it will have problems. I have fixed this problem in version 0.0.4)
> 

I am using windows 10 and gVim. The path is ok it only missing the name of the vault name

like this should be the real path: 
<path to vault>/<vault name>/<relative path to note>

But the non existent note it is opening path is this:
<path to vault>/<relative path to note>

I switched to "open with" plugin which basically doing what your plugin does but with any app and it works fine. But I would help with identification of this bug if I can.

**Comment by yekingyan** [comment]
Thanks for your feedback, in fact, “Open with” is a much more feature-rich plugin.
